### ISSUE TITLE
Missing dataset in the benchmark

### ISSUE THREAD

**Issue by moonboy12138** [Cuzyoung/CrossEarth#3]
Great work! I noticed that the WHU building dataset is not included in the [link](https://pan.baidu.com/s/1PrCKuYaSLW31pZ-P7e95xw?pwd=h78a#list/path=%2FCrossEarth-Benchmark). Will it be added soon?

**Comment by Cuzyoung** [comment]
Sorry for our late update.  There's been so much going on lately. The WHU Building dataset will be updated in these days (will not be later than next Friday.

**Comment by Cuzyoung** [comment]
Thanks for your issue~ We have uploaded the WHU Building Dataset. You can download it from our  [huggingface page](https://huggingface.co/datasets/Cusyoung/CrossEarth-Benchmark/tree/main). If there are some other problems, welcome issue again~
